import { Link } from 'react-router-dom';
import { PublicHeader } from '../../components/Layout';
import { Badge, Card, Icon, LinkButton } from '../../components/ui';
import { SOURCE_FRAMEWORK } from '../../domain/seed';
export default function Landing() {
  return <div className="public-page"><PublicHeader/><main><section className="hero"><div className="hero-copy"><Badge tone="amber">TALEED BUSINESS CAPABILITIES</Badge><h1>Stronger procurement<br/>starts with <em>clarity.</em></h1><p>Understand where your procurement function stands. Discover the capabilities to strengthen, and turn insight into focused action.</p><div className="hero-actions"><LinkButton to="/register">Start your assessment <Icon name="arrow"/></LinkButton><LinkButton to="/login" variant="secondary">Explore the live demo</LinkButton></div><div className="hero-facts"><span><Icon name="file"/>40 Yes/No questions</span><span><Icon name="grid"/>4 capability areas</span><span><Icon name="check"/>Immediate results</span></div><p className="hero-disclaimer">Interactive local prototype. Use synthetic information only. No real account, email service or cloud storage is connected.</p></div><div className="hero-visual" aria-label="Illustrative assessment results"><div className="hero-grid"/><Card className="hero-preview"><div className="row-between"><span className="eyebrow">YOUR PROCUREMENT MATURITY</span><Badge tone="developing">Developing</Badge></div><div className="preview-number">60.0<span>%</span></div><p>A clearer view. A stronger next step.</p><div className="preview-bars">{[60,40,80,60].map((v,i) => <div key={i}><span>{['Category management','Spend analysis','Strategic sourcing','Supplier relationships'][i]}</span><div><b style={{width:`${v}%`}}/></div><strong>{v}%</strong></div>)}</div><div className="preview-foot"><Icon name="flag"/><span>3 relative focus areas identified</span></div></Card><div className="hero-floating"><span className="icon-box"><Icon name="check"/></span><div><strong>Practical next steps</strong><small>Selected from your domain results</small></div></div><span className="illustrative-label">ILLUSTRATIVE RESULT · NOT A MARKET BENCHMARK</span></div></section>
    <section className="public-section"><div className="section-intro"><p className="eyebrow">FOUR PERSPECTIVES. ONE CLEAR PICTURE.</p><h2>See the capabilities behind performance.</h2><p>A structured diagnostic for CEOs, procurement leaders and authorized company representatives.</p></div><div className="domain-card-grid">{SOURCE_FRAMEWORK.domains.map((domain,i) => <Card key={domain.key}><span className="domain-number">0{i+1}</span><h3>{domain.name}</h3><p>{['Build category ownership, clear strategies and consistent performance reviews.','Understand spend visibility, data quality and decision-ready insights.','Assess sourcing discipline, supplier selection and realized value.','Strengthen supplier governance, performance and collaboration.'][i]}</p><small>10 questions · 25% of the overall score</small></Card>)}</div></section>
    <section className="public-section process-section"><div><p className="eyebrow">A GUIDED JOURNEY</p><h2>From assessment<br/>to meaningful action.</h2><Link to="/methodology" className="text-link">Read the methodology <Icon name="arrow"/></Link></div><div className="process-list">{[['Identify your company','Create your demo account and confirm your authority to respond.'],['Reflect on your practices','Answer four guided sections. Your progress is saved in this browser.'],['Understand your next steps','Review your answers, submit and receive a result with relevant recommendations.']].map(([title,text],i) => <div key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
    <section className="public-cta"><div><h2>A better conversation starts here.</h2><p>No spreadsheet versions. No hidden scoring. A focused view of your capabilities.</p></div><LinkButton to="/register">Begin your assessment <Icon name="arrow"/></LinkButton></section></main><footer className="public-footer"><span>Source framework: Aramco Taleed & Roland Berger · v1.0.0</span><nav><Link to="/privacy">Prototype privacy</Link><Link to="/methodology">Methodology</Link></nav></footer></div>;
}
