import { useEffect, useState } from 'react';
import { Link, Navigate, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useCommand, useCurrentUser, useDatabase } from '../../app/hooks';
import { useAppSelector } from '../../app/store';
import { Alert, Badge, Button, Card, Dialog, EmptyState, Icon, LinkButton, PageHeading, Progress } from '../../components/ui';
import { completion } from '../../domain/scoring';
import { isCycleOpen, validProfile } from '../../domain/policies';
import { demoNow } from '../../domain/seed';

export function AssessmentPage() {
  const {id='',section='1'}=useParams(); const db=useDatabase(); const user=useCurrentUser();
  const {run,busy}=useCommand(); const navigate=useNavigate(); const [params]=useSearchParams();
  const [showMissing,setShowMissing]=useState(false);
  const assessment=db.assessments[id]; const index=Number(section)-1;
  const framework=assessment?db.frameworks[assessment.frameworkVersion]?.content:undefined;
  const domain=Number.isInteger(index)?framework?.domains[index]:undefined;
  useEffect(()=>{setShowMissing(false); const target=params.get('question'); if(target){const frame=requestAnimationFrame(()=>{const element=document.getElementById(`question-${target}`);element?.scrollIntoView({block:'center'});element?.querySelector('input')?.focus();});return()=>cancelAnimationFrame(frame);}},[id,section,params]);
  if(!assessment||assessment.orgId!==user.orgId||!domain||!framework)return <EmptyState title="Assessment unavailable" action={<LinkButton to="/app/dashboard">Return to workspace</LinkButton>}>This assessment or section is not available to your company.</EmptyState>;
  if(assessment.status==='submitted')return <Navigate to={`/app/results/${id}`} replace/>;
  const cycle=db.cycles[assessment.cycleId]; const editable=!!cycle&&isCycleOpen(cycle,demoNow())&&db.organizations[assessment.orgId]?.active;
  const missing=domain.questions.filter((question)=>assessment.answers[question.id]===null);
  const next=()=>{if(missing.length){setShowMissing(true);requestAnimationFrame(()=>document.getElementById(`question-${missing[0]?.id}`)?.querySelector('input')?.focus());return;}navigate(index===3?`/app/assessment/${id}/review`:`/app/assessment/${id}/${index+2}`);};
  return <><PageHeading eyebrow={`${cycle?.label??'ASSESSMENT'} · REVISION ${assessment.revision}`} title={domain.name} description={`Section ${index+1} of 4 · Reflect on your current procurement practices.`} actions={<Button variant="secondary" disabled={busy} onClick={()=>navigate('/app/dashboard')}><Icon name="check"/>Save & exit</Button>}/>
    {!editable&&<Alert kind="warning">Editing is paused because this cycle is closed or the organization is paused. Saved answers remain visible.</Alert>}
    {assessment.correctionReason&&<Alert kind="warning" title="Correction draft">{assessment.correctionReason} Your previous submission remains effective until this revision is submitted.</Alert>}
    <Card className="assessment-progress"><div className="row-between"><strong>Overall completion</strong><span>{completion(assessment.answers)} / 40 questions</span></div><Progress value={completion(assessment.answers)}/></Card>
    <div className="assessment-layout"><aside className="assessment-aside"><nav aria-label="Assessment sections" className="stepper">{framework.domains.map((d,i)=>{const count=d.questions.filter((q)=>assessment.answers[q.id]!==null).length;return <Link key={d.key} to={`/app/assessment/${id}/${i+1}`} className={`step ${index===i?'active':''}`} aria-current={index===i?'step':undefined}><span className={`step-number ${count===10?'done':''}`}>{count===10?<Icon name="check" size={16}/>:i+1}</span><span><strong>{d.name}</strong><small>{count} of 10 answered</small></span></Link>;})}<Link className="step" to={`/app/assessment/${id}/review`}><span className="step-number"><Icon name="file" size={16}/></span><span><strong>Review & submit</strong><small>Check all 40 answers</small></span></Link></nav><Card className="guidance-card"><Icon name="info"/><h3>Answer honestly.</h3><p><strong>Yes</strong><br/>Consistently in place across the function.</p><p><strong>No</strong><br/>Missing or only partly implemented.</p><small>There is no N/A option or partial credit in the source framework.</small></Card></aside>
      <div className="question-list"><div className="row-between section-count"><h2>{10-missing.length} of 10 answered</h2><Badge tone={missing.length?'blue':'success'}>{missing.length?'In progress':'Section complete'}</Badge></div>
        {showMissing&&missing.length>0&&<Alert kind="error" title={`${missing.length} unanswered question${missing.length===1?'':'s'}`}>Answer every question in this section before continuing, or use the section navigation to return later.</Alert>}
        {domain.questions.map((question)=>{const value=assessment.answers[question.id];const invalid=showMissing&&value===null;return <fieldset id={`question-${question.id}`} key={question.id} className={`question-card ${invalid?'question-error':''}`} aria-describedby={invalid?`missing-${question.id}`:undefined} disabled={busy||!editable}><legend><span className="question-id">{question.id}</span>{question.text}</legend><div className="answer-options">{(['yes','no'] as const).map((answer)=><label key={answer} className={`answer-option ${value===answer?'selected':''}`}><input type="radio" name={`answer-${question.id}`} value={answer} checked={value===answer} onChange={()=>{void run({type:'answer',assessmentId:id,questionId:question.id,value:answer});}}/><span><strong>{answer==='yes'?'Yes':'No'}</strong><small>{answer==='yes'?'Consistently in place':'Missing or partly in place'}</small></span>{value===answer&&<Icon name="check" size={18}/>}</label>)}</div><div className="question-footer"><small>{value===null?'Choose one answer':'Saved in this browser'}</small>{value!==null&&<Button variant="ghost" onClick={()=>{void run({type:'answer',assessmentId:id,questionId:question.id,value:null});}} aria-label={`Clear answer ${question.id}`}>Clear answer</Button>}</div>{invalid&&<span id={`missing-${question.id}`} className="field-error">Choose Yes or No for this question.</span>}</fieldset>;})}
        <Card className="assessment-actions"><Button variant="secondary" disabled={busy} onClick={()=>navigate(index===0?'/app/dashboard':`/app/assessment/${id}/${index}`)}><Icon name="back"/>{index===0?'Workspace':'Previous section'}</Button><span>{10-missing.length}/10 answered</span><Button disabled={busy} onClick={next}>{index===3?'Review all answers':'Continue'}<Icon name="arrow"/></Button></Card>
      </div>
    </div></>;
}
export function ReviewPage() {
  const {id=''}=useParams();const db=useDatabase();const user=useCurrentUser();const {run,busy}=useCommand();const navigate=useNavigate();
  const [declaration,setDeclaration]=useState(false);const [confirm,setConfirm]=useState(false);const [attempted,setAttempted]=useState(false);
  const error=useAppSelector((s)=>s.ui.error);
  const assessment=db.assessments[id];const framework=assessment?db.frameworks[assessment.frameworkVersion]?.content:undefined;
  if(!assessment||assessment.orgId!==user.orgId||!framework)return <EmptyState title="Assessment unavailable" action={<LinkButton to="/app/dashboard">Return to workspace</LinkButton>}>You cannot review this company's assessment.</EmptyState>;
  if(assessment.status==='submitted')return <Navigate to={`/app/results/${id}`} replace/>;
  const unanswered=framework.domains.flatMap((d,i)=>d.questions.filter((q)=>assessment.answers[q.id]===null).map((q)=>({...q,section:i+1})));
  const org=db.organizations[assessment.orgId];const cycle=db.cycles[assessment.cycleId];
  const eligible=!!cycle&&isCycleOpen(cycle,demoNow())&&!!org?.active&&validProfile(org)&&unanswered.length===0;
  return <><PageHeading eyebrow={`FINAL CHECK · REVISION ${assessment.revision}`} title="Review your assessment" description="Check every answer. Once submitted, this revision becomes a read-only record." actions={<LinkButton variant="secondary" to="/app/dashboard">Save & exit</LinkButton>}/>
    <div className="review-layout"><div className="stack"><Card><div className="row-between"><h2>Readiness check</h2><Badge tone={eligible?'success':'amber'}>{eligible?'Ready to submit':'Action required'}</Badge></div><Progress value={completion(assessment.answers)}/><p><strong>{completion(assessment.answers)} of 40 answers</strong> completed across four domains.</p>{unanswered.length>0&&<Alert kind="warning" title={`${unanswered.length} answer${unanswered.length===1?' is':'s are'} still missing`}>No maturity result is calculated for an incomplete assessment.<div className="missing-links">{unanswered.map((q)=><Link key={q.id} to={`/app/assessment/${id}/${q.section}?question=${q.id}`} aria-label={`Answer missing question ${q.id}`}>{q.id}</Link>)}</div></Alert>}{!validProfile(org)&&<Alert kind="error">Complete the <Link to="/app/profile">company profile and authority declaration</Link>.</Alert>}{(!cycle||!isCycleOpen(cycle,demoNow())||!org?.active)&&<Alert kind="warning">The cycle is closed or your organization is paused. Submission is not available.</Alert>}</Card>
    {framework.domains.map((domain,i)=><details className="review-domain" key={domain.key} open={domain.questions.some((q)=>assessment.answers[q.id]===null)}><summary><span><span className="domain-number">0{i+1}</span>{domain.name}</span><Badge tone={domain.questions.every((q)=>assessment.answers[q.id]!==null)?'success':'amber'}>{domain.questions.filter((q)=>assessment.answers[q.id]!==null).length}/10 answered</Badge></summary><div className="review-answers">{domain.questions.map((q)=><div key={q.id}><span className="question-id">{q.id}</span><p>{q.text}</p><Badge tone={assessment.answers[q.id]===null?'amber':'neutral'}>{assessment.answers[q.id]===null?'Unanswered':assessment.answers[q.id]==='yes'?'Yes':'No'}</Badge><Link to={`/app/assessment/${id}/${i+1}?question=${q.id}`} aria-label={`Edit answer ${q.id}`}>Edit</Link></div>)}</div></details>)}</div>
    <aside className="stack review-summary"><Card><h2>Submission summary</h2><dl className="definition-list"><dt>Company</dt><dd>{org?.name}</dd><dt>Respondent</dt><dd>{user.name}<small className="block">{user.jobTitle}</small></dd><dt>Cycle</dt><dd>{cycle?.label}</dd><dt>Framework</dt><dd>v{assessment.frameworkVersion}</dd><dt>Revision</dt><dd>{assessment.revision}</dd></dl><div className="divider"/><label className="checkbox"><input type="checkbox" checked={declaration} onChange={(e)=>setDeclaration(e.target.checked)}/><span>I confirm these answers accurately reflect the company's current procurement practices and I am authorized to submit.</span></label>{attempted&&!declaration&&<p className="field-error">Confirm the declaration before submitting.</p>}<Button className="full-width" disabled={busy||!eligible} onClick={()=>{setAttempted(true);if(declaration&&eligible)setConfirm(true);}}>Submit assessment <Icon name="arrow"/></Button>{!eligible&&<small className="muted block">Complete the readiness items to enable submission.</small>}</Card><Alert>Results appear immediately after a successful local save. There is no mandatory Taleed approval gate or certification.</Alert></aside></div>
    <Dialog open={confirm} title="Submit this assessment?" onClose={()=>setConfirm(false)}><p>You are submitting <strong>revision {assessment.revision}</strong> for <strong>{org?.name}</strong>.</p><p>Your answers and result will become read-only. A Super Admin can later open a correction revision without deleting this one.</p>{error&&<Alert kind="error">{error}</Alert>}<div className="dialog-actions"><Button variant="secondary" onClick={()=>setConfirm(false)} disabled={busy}>Keep reviewing</Button><Button disabled={busy} onClick={async()=>{const saved=await run({type:'submit',assessmentId:id,declaration});if(saved){setConfirm(false);navigate(`/app/results/${id}`);}}}>{busy?'Saving submission…':'Confirm submission'}</Button></div></Dialog>
  </>;
}
