import { useSearchParams } from 'react-router-dom';
import { useDatabase } from '../../app/hooks';
import { effectiveSubmissions } from '../../domain/policies';
import { Alert, Badge, BandBadge, Card, EmptyState, Field, PageHeading } from '../../components/ui';
export default function Compare() {
  const db=useDatabase(); const [params,setParams]=useSearchParams();
  const cycleId=params.get('cycle')??Object.values(db.cycles).sort((a,b)=>b.opensAt.localeCompare(a.opensAt))[0]?.id??'';
  const rows=effectiveSubmissions(db,cycleId);const ids=(params.get('ids')??'').split(',').filter(Boolean);
  const selected=rows.filter((a)=>ids.includes(a.id)).slice(0,4);
  const toggle=(id:string,checked:boolean)=>{const next=checked?[...ids.filter((x)=>rows.some((a)=>a.id===x)),id].slice(0,4):ids.filter((x)=>x!==id);setParams({cycle:cycleId,ids:next.join(',')});};
  return <><PageHeading eyebrow="LIKE-FOR-LIKE COMPARISON" title="Compare company results" description="Select two to four effective submissions from the same assessment cycle and framework."/><Card><div className="card-heading"><Field label="Assessment cycle" htmlFor="compare-cycle"><select id="compare-cycle" value={cycleId} onChange={(e)=>setParams({cycle:e.target.value})}>{Object.values(db.cycles).map((c)=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field><Badge>Framework {db.cycles[cycleId]?.frameworkVersion}</Badge></div><div className="company-picker">{rows.map((a)=><label className={`company-choice ${ids.includes(a.id)?'selected':''}`} key={a.id}><input type="checkbox" checked={ids.includes(a.id)} disabled={!ids.includes(a.id)&&selected.length>=4} onChange={(e)=>toggle(a.id,e.target.checked)}/><span><strong>{a.snapshot?.organization.name}</strong><small>{a.snapshot?.organization.sector}</small></span></label>)}</div></Card><Alert>These comparisons show self-reported results from participating companies. They are available only in the staff demo workspace and are not a public ranking or an external benchmark.</Alert>
    {selected.length<2?<EmptyState title="Choose at least two companies">Select up to four companies above to build a side-by-side comparison.</EmptyState>:<Card className="table-card"><div className="table-wrap"><table className="comparison-table"><caption className="sr-only">Like-for-like company capability comparison</caption><thead><tr><th>Measure</th>{selected.map((a)=><th key={a.id}>{a.snapshot?.organization.name}<small className="block">Revision {a.revision}</small></th>)}</tr></thead><tbody><tr className="comparison-total"><th>Overall maturity</th>{selected.map((a)=><td key={a.id}><strong>{a.snapshot?.result.overall.toFixed(1)}%</strong>{a.snapshot&&<BandBadge band={a.snapshot.result.band}/>}</td>)}</tr>{db.frameworks[db.cycles[cycleId]?.frameworkVersion??'']?.content.domains.map((d,i)=><tr key={d.key}><th>{d.name}</th>{selected.map((a)=>{const r=a.snapshot?.result.domains[i];return <td key={a.id}>{r&&<><strong>{r.score.toFixed(1)}%</strong><div><BandBadge band={r.band}/></div></>}</td>;})}</tr>)}<tr><th>Consistent practices</th>{selected.map((a)=><td key={a.id}>{a.snapshot?.result.yes} / 40</td>)}</tr></tbody></table></div></Card>}</>;
}
