import { useState } from 'react';
import { repository, replaceDemoDataset, useAppSelector } from '../../app/store';
import type { Database } from '../../domain/types';
import { MAX_BACKUP_BYTES, parseDatabase } from '../../domain/validation';
import { seedDatabase } from '../../domain/seed';
import { downloadBlob, downloadJson } from '../../infrastructure/downloads';
import { PublicHeader } from '../../components/Layout';
import { Alert, Button, Card, Dialog, Field, Icon, PageHeading } from '../../components/ui';
export default function DataControls({recovery=false}:{recovery?:boolean}) {
  const db=useAppSelector((s)=>s.data);const bootError=useAppSelector((s)=>s.ui.bootError);
  const [candidate,setCandidate]=useState<Database|null>(null);const [filename,setFilename]=useState('');
  const [error,setError]=useState('');const [mode,setMode]=useState<'reset'|'import'|null>(null);const [confirmation,setConfirmation]=useState('');const [busy,setBusy]=useState(false);
  const exportRaw=()=>{try{const raw=repository.raw();if(raw===null)throw new Error('No saved local dataset exists.');downloadBlob('taleed-local-data-recovery.txt',new Blob([raw],{type:'text/plain;charset=utf-8'}));}catch(e){setError(e instanceof Error?e.message:'Cannot read local data.');}};
  const content=<><PageHeading eyebrow={recovery?'SAFE STARTUP RECOVERY':'SUPER ADMIN · LOCAL ENVIRONMENT'} title={recovery?'Your local data needs attention':'Demo data controls'} description="Export, validate and deliberately replace this prototype's dataset. No other application storage is modified."/>{recovery&&<Alert kind="error" title="The saved dataset could not be opened">{bootError} The original data has not been silently replaced.</Alert>}<Alert kind="warning">These controls replace all companies, assessments and users in this browser's prototype dataset. Export a backup first. Browser-local storage is neither a shared database nor a secure backup service.</Alert>{error&&<Alert kind="error">{error}</Alert>}
    <div className="two-column"><Card><span className="icon-box"><Icon name="download"/></span><h2>Export before changing data</h2><p>Keep a JSON backup of the current prototype. Treat any exported file as potentially containing names and company answers.</p><div className="button-row">{db&&<Button onClick={()=>downloadJson('taleed-procurement-backup.json',db)}>Export validated JSON</Button>}<Button variant="secondary" onClick={exportRaw}>Export raw local data</Button></div><p className="muted">Raw export is useful when JSON is corrupted or from an unsupported schema version.</p></Card><Card><span className="icon-box"><Icon name="refresh"/></span><h2>Restore the demonstration</h2><p>Reload the original synthetic companies, staff accounts, 12-answer draft and submitted examples.</p><Button variant="danger" onClick={()=>{setMode('reset');setConfirmation('');}}>Reset demo dataset</Button><small className="muted block">Nothing happens until you explicitly confirm.</small></Card></div>
    <Card><h2>Import a validated backup</h2><p>Choose a JSON backup. Validation checks the schema, record relationships, question IDs, answer values, correction chains and recomputed result snapshots before enabling import.</p><Field label="Backup file" htmlFor="backup-file" hint="JSON only, up to 3.5 MB. Selecting a file does not replace any data."><input id="backup-file" type="file" accept="application/json,.json" onChange={async(e)=>{const file=e.target.files?.[0];setCandidate(null);setError('');if(!file)return;try{if(file.size>MAX_BACKUP_BYTES)throw new Error('Choose a backup under 3.5 MB.');const value=parseDatabase(await file.text());setCandidate(value);setFilename(file.name);}catch(err){setError(err instanceof Error?err.message:'Invalid backup file.');}}}/></Field>{candidate&&<div className="import-preview"><Alert kind="success" title="Backup validation passed">{filename}: {Object.keys(candidate.organizations).length} companies, {Object.keys(candidate.users).length} users, {Object.keys(candidate.assessments).length} assessments. Schema v{candidate.schemaVersion}.</Alert><Button onClick={()=>{setMode('import');setConfirmation('');}}>Review and replace local data</Button></div>}</Card>
    <Card><h2>Storage and session boundaries</h2><p>The domain dataset is stored under one versioned key. The selected demo user ID is session-only. Passwords, authentication tokens, files and UI component state are not persisted.</p><p>Writes complete before the UI reports success. Cross-tab changes pause editing. Browsers without the Web Locks API should be used in one tab only; localStorage is not a transactional multi-user database.</p>{!recovery&&<p className="muted">Current dataset revision: {db?.revision} · Browser data is not synchronized with another device.</p>}</Card>
    <Dialog open={mode!==null} title={mode==='import'?'Replace data from this backup?':'Reset all prototype data?'} onClose={()=>setMode(null)}><p>This replaces the current dataset and signs out every local demo identity in this tab. It cannot be undone without an exported backup.</p><Field label="Type REPLACE to confirm" htmlFor="replace-confirmation"><input id="replace-confirmation" value={confirmation} autoComplete="off" onChange={(e)=>setConfirmation(e.target.value)}/></Field>{error&&<Alert kind="error">{error}</Alert>}<div className="dialog-actions"><Button variant="secondary" disabled={busy} onClick={()=>setMode(null)}>Cancel</Button><Button variant="danger" disabled={confirmation!=='REPLACE'||busy} onClick={async()=>{setBusy(true);setError('');try{const next=mode==='import'?candidate:seedDatabase();if(!next)throw new Error('No validated backup selected.');await replaceDemoDataset(next,confirmation,recovery);}catch(e){setError(e instanceof Error?e.message:'Data replacement failed.');}finally{setBusy(false);}}}>{busy?'Replacing…':'Replace local dataset'}</Button></div></Dialog></>;
  return recovery?<div className="public-page"><PublicHeader/><main className="recovery-layout">{content}</main></div>:content;
}
