import { useState } from 'react';
import { useCommand, useCurrentUser, useDatabase } from '../../app/hooks';
import { useAppSelector } from '../../app/store';
import { canManage } from '../../domain/policies';
import { BANDS, BAND_LABELS } from '../../domain/scoring';
import type { Band } from '../../domain/types';
import { Alert, Badge, Button, Card, Dialog, Field, Icon, PageHeading, formatDate } from '../../components/ui';
export default function Frameworks() {
  const db=useDatabase();const user=useCurrentUser();const {run,busy}=useCommand();const error=useAppSelector((s)=>s.ui.error);
  const [version,setVersion]=useState('1.0.0');const [band,setBand]=useState<Band>('foundational');
  const [mode,setMode]=useState<'clone'|'publish'|null>(null);const [newVersion,setNewVersion]=useState('1.1.0');const [reference,setReference]=useState('');
  const [editor,setEditor]=useState<{contentType:'question'|'recommendation';targetId:string;text:string}|null>(null);
  const record=db.frameworks[version]??Object.values(db.frameworks)[0];if(!record)return null;
  const f=record.content;
  return <><PageHeading eyebrow="CONTROLLED CONTENT" title="Framework library" description="The complete source question bank, scoring contract and domain-specific recommendation library." actions={canManage(user)&&<><Button variant="secondary" onClick={()=>setMode('clone')}><Icon name="file"/>Prepare new version</Button>{record.status==='draft'&&<Button onClick={()=>setMode('publish')}>Publish demo version</Button>}</>}/>
    <Card className="framework-overview"><div className="row-between"><Field label="Framework version" htmlFor="framework-version"><select id="framework-version" value={record.version} onChange={(e)=>setVersion(e.target.value)}>{Object.values(db.frameworks).map((r)=><option key={r.version} value={r.version}>v{r.version} · {r.status}</option>)}</select></Field><Badge tone={record.status==='published'?'success':'amber'}>{record.status} · prototype only</Badge></div><h2>{f.title}</h2><div className="framework-facts"><span><strong>40</strong>Questions</span><span><strong>4</strong>Equal domains</span><span><strong>64</strong>Recommendation actions</span><span><strong>16</strong>Actions per result</span></div><p className="muted">Source: {f.sourceFile} · {f.attribution}</p><p className="muted">Published: {formatDate(record.publishedAt)} · Reference: {record.approvalReference||'Pending'}</p></Card>
    <Alert kind="warning">Publication here is simulated. Approval of this prototype's design is not treated as formal approval of the questionnaire, source rights, privacy wording or live scoring framework. Published content and past result snapshots are not edited in place.</Alert>
    <div className="two-column"><Card><h2>Scoring rules</h2><p>Yes = 1 point; No = 0 points. Unanswered is not No. All 40 answers are required before a result is finalized.</p><p>Overall = Yes ÷ 40 × 100. Each domain = Yes ÷ 10 × 100. There is no N/A or partial-credit answer.</p><p>Priority domains are the three lowest scores, with ties in source order. Recommendations use each domain's own band, not the overall band.</p></Card><Card><h2>Maturity bands</h2><dl className="band-definitions">{BANDS.map((b,i)=><div key={b}><dt><Badge tone={b}>{BAND_LABELS[b]}</Badge></dt><dd>{['0–40%','>40–65%','>65–80%','>80–100%'][i]}</dd></div>)}</dl><small>Classification uses the exact, unrounded score.</small></Card></div>
    <div className="section-title"><h2>Questions and recommendations</h2><Field label="Recommendation band" htmlFor="framework-band"><select id="framework-band" value={band} onChange={(e)=>setBand(e.target.value as Band)}>{BANDS.map((b)=><option key={b} value={b}>{BAND_LABELS[b]}</option>)}</select></Field></div>
    <div className="stack">{f.domains.map((domain)=><details className="framework-domain" key={domain.key}><summary><span><span className="domain-number">0{domain.order}</span>{domain.name}</span><Badge>10 questions · 4 selected actions</Badge></summary><div className="framework-domain-body"><div><h3>Exact source questions</h3>{domain.questions.map((q)=><div className="catalogue-question" key={q.id}><strong>{q.id}</strong><p>{q.text}<small>{q.sourceCell}</small></p>{canManage(user)&&record.status==='draft'&&<Button variant="ghost" onClick={()=>setEditor({contentType:'question',targetId:q.id,text:q.text})} aria-label={`Edit draft question ${q.id}`}>Edit</Button>}</div>)}</div><div><h3>{BAND_LABELS[band]} recommendations</h3><ol className="action-list">{domain.recommendations[band].map((a)=><li key={a.id}>{a.text}<small className="block muted">{a.sourceCell}</small>{canManage(user)&&record.status==='draft'&&<Button variant="ghost" onClick={()=>setEditor({contentType:'recommendation',targetId:a.id,text:a.text})} aria-label={`Edit recommendation ${a.id}`}>Edit draft action</Button>}</li>)}</ol></div></div></details>)}</div>
    <Dialog open={mode==='clone'} title="Prepare a new framework version" onClose={()=>setMode(null)}><p>Create a draft copy of v{record.version}. All source content is copied. You can then edit draft question and recommendation text. Question IDs, domain structure, weights and score thresholds remain fixed; published versions are read-only.</p><Field label="New version" htmlFor="new-framework-version" hint="Use an unused semantic version such as 1.1.0."><input id="new-framework-version" value={newVersion} onChange={(e)=>setNewVersion(e.target.value)}/></Field>{error&&<Alert kind="error">{error}</Alert>}<div className="dialog-actions"><Button variant="secondary" onClick={()=>setMode(null)}>Cancel</Button><Button disabled={busy||!/^\d+\.\d+\.\d+$/.test(newVersion)} onClick={async()=>{const id=await run({type:'cloneFramework',sourceVersion:record.version,version:newVersion});if(id){setVersion(newVersion);setMode(null);}}}>Create draft version</Button></div></Dialog>
    <Dialog open={mode==='publish'} title="Publish this demo version?" onClose={()=>setMode(null)}><Alert kind="warning">This is a local publication simulation. It does not assert that the client has approved the content.</Alert><Field label="Approval reference (simulation)" htmlFor="approval-reference" hint="At least eight characters. Use a clearly labelled demo reference."><input id="approval-reference" value={reference} onChange={(e)=>setReference(e.target.value)} placeholder="DEMO-APPROVAL-001"/></Field>{error&&<Alert kind="error">{error}</Alert>}<div className="dialog-actions"><Button variant="secondary" onClick={()=>setMode(null)}>Cancel</Button><Button disabled={busy||reference.trim().length<8} onClick={async()=>{const id=await run({type:'publishFramework',version:record.version,approvalReference:reference});if(id)setMode(null);}}>Confirm simulated publication</Button></div></Dialog>
    <Dialog open={!!editor} title="Edit draft content" onClose={()=>setEditor(null)}><Alert>Only this unpublished draft changes. Source v1.0.0 and earlier result snapshots remain unchanged. Formal content approval is required before real publication.</Alert><Field label="Content text *" htmlFor="draft-content-text" hint="10–2,000 characters. The source identifier and scoring are not editable."><textarea id="draft-content-text" rows={7} maxLength={2000} value={editor?.text??''} onChange={(event)=>setEditor((current)=>current?{...current,text:event.target.value}:null)}/></Field>{error&&<Alert kind="error">{error}</Alert>}<div className="dialog-actions"><Button variant="secondary" onClick={()=>setEditor(null)}>Cancel</Button><Button disabled={busy||!editor||editor.text.trim().length<10} onClick={async()=>{if(!editor)return;const id=await run({type:'updateDraftContent',version:record.version,...editor});if(id)setEditor(null);}}>Save draft text</Button></div></Dialog>
  </>;
}
