import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useCommand, useCurrentUser, useDatabase } from '../../app/hooks';
import { useAppSelector } from '../../app/store';
import { canManage, effectiveSubmissions } from '../../domain/policies';
import { Alert, Badge, BandBadge, Button, Card, Dialog, EmptyState, Field, Icon, LinkButton, PageHeading, formatDate } from '../../components/ui';
import type { Assessment } from '../../domain/types';
export function Organizations() {
  const db=useDatabase(); const [search,setSearch]=useState('');const [status,setStatus]=useState('');
  const orgs=Object.values(db.organizations).filter((o)=>o.name.toLowerCase().includes(search.toLowerCase())&&(!status||(status==='active'&&o.active)||(status==='paused'&&!o.active)));
  return <><PageHeading eyebrow="PARTICIPATION" title="Organizations" description="Company profiles, assessment participation and submitted results in one place."/>
    <Card className="filters compact"><Field label="Company name" htmlFor="org-search"><input id="org-search" type="search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search organizations…"/></Field><Field label="Account status" htmlFor="org-status"><select id="org-status" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">All organizations</option><option value="active">Active</option><option value="paused">Paused</option></select></Field><span className="filter-count">{orgs.length} organizations</span></Card>
    {orgs.length?<Card className="table-card"><div className="table-wrap"><table><caption className="sr-only">Organization directory</caption><thead><tr><th>Organization</th><th>Country</th><th>Size</th><th>Status</th><th>Participation</th><th>Details</th></tr></thead><tbody>{orgs.map((o)=>{const all=Object.values(db.assessments).filter((a)=>a.orgId===o.id);return <tr key={o.id}><td><strong>{o.name}</strong><small className="block">{o.registrationId||'No registration reference'}</small></td><td>{o.country}</td><td>{o.size}</td><td><Badge tone={o.active?'success':'amber'}>{o.active?'Active':'Paused'}</Badge></td><td>{all.filter((a)=>a.status==='submitted').length} submitted revisions<small className="block">{all.filter((a)=>a.status==='draft').length} open drafts</small></td><td><Link to={`/app/organizations/${o.id}`}>View company</Link></td></tr>;})}</tbody></table></div></Card>:<EmptyState title="No organizations found">Try a different name or account-status filter.</EmptyState>}</>;
}
export function OrganizationDetail() {
  const {id=''}=useParams();const db=useDatabase();const user=useCurrentUser();const {run,busy}=useCommand();
  const error=useAppSelector((s)=>s.ui.error);const [correction,setCorrection]=useState<Assessment|null>(null);const [reason,setReason]=useState('');const [pause,setPause]=useState(false);
  const org=db.organizations[id];if(!org)return <EmptyState title="Organization not found" action={<LinkButton to="/app/organizations">Organization directory</LinkButton>}>This record does not exist in the current local dataset.</EmptyState>;
  const submissions=Object.values(db.assessments).filter((a)=>a.orgId===id&&a.status==='submitted').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
  const drafts=Object.values(db.assessments).filter((a)=>a.orgId===id&&a.status==='draft');
  const effective=new Set(effectiveSubmissions(db).map((a)=>a.id));
  return <><PageHeading eyebrow="ORGANIZATION DETAIL" title={org.name} description={`${org.country} · ${org.size} employees`} actions={canManage(user)&&<Button variant={org.active?'secondary':'primary'} onClick={()=>setPause(true)}>{org.active?'Pause organization':'Resume organization'}</Button>}/><div className="two-column"><Card><div className="card-heading"><h2>Company information</h2><Badge tone={org.active?'success':'amber'}>{org.active?'Active':'Paused'}</Badge></div><dl className="definition-list"><dt>Company reference</dt><dd>{org.registrationId||'Not provided'}</dd><dt>Authority declaration</dt><dd>{org.authorityConfirmed?'Confirmed by respondent':'Pending'}</dd><dt>Data context</dt><dd>Synthetic local demonstration</dd></dl></Card><Card><h2>Company representatives</h2>{Object.values(db.users).filter((u)=>u.orgId===id).map((u)=><div className="person-row" key={u.id}><span className="avatar">{u.name.slice(0,1)}</span><div><strong>{u.name}</strong><small>{u.jobTitle} · {u.email}</small></div><Badge tone={u.active?'success':'amber'}>{u.active?'Active':'Paused'}</Badge></div>)}</Card></div>
    {drafts.length>0&&<Alert title={`${drafts.length} draft${drafts.length===1?' is':'s are'} in progress`}>Draft answers are not exposed in staff views. {drafts.map((a)=><p key={a.id}>{db.cycles[a.cycleId]?.label} · Revision {a.revision}{a.supersedesId?' · Correction draft':''}</p>)}</Alert>}
    <div className="section-title"><h2>Submitted assessment history</h2><span>{submissions.length} revisions</span></div>{submissions.length?<Card className="table-card"><div className="table-wrap"><table><caption className="sr-only">Company submitted assessments</caption><thead><tr><th>Cycle</th><th>Revision</th><th>Result</th><th>Record status</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>{submissions.map((a)=><tr key={a.id}><td>{db.cycles[a.cycleId]?.label}</td><td>v{a.revision}</td><td>{a.snapshot&&<><strong>{a.snapshot.result.overall.toFixed(1)}%</strong><br/><BandBadge band={a.snapshot.result.band}/></>}</td><td><Badge tone={effective.has(a.id)?'success':'neutral'}>{effective.has(a.id)?'Effective':'Earlier revision'}</Badge></td><td>{formatDate(a.submittedAt)}</td><td><div className="table-actions"><Link to={`/app/results/${a.id}`}>View result</Link>{canManage(user)&&effective.has(a.id)&&<Button variant="ghost" disabled={busy||drafts.some((d)=>d.cycleId===a.cycleId)} onClick={()=>{setCorrection(a);setReason('');}}><Icon name="refresh" size={16}/>Open correction</Button>}</div></td></tr>)}</tbody></table></div></Card>:<EmptyState title="No submitted assessments yet">The company's final results will appear after its authorized representative submits all 40 answers.</EmptyState>}
    <Dialog open={!!correction} title="Open a controlled correction" onClose={()=>setCorrection(null)}><Alert kind="warning">The submitted result stays unchanged and effective until the Company Champion completes and submits a new revision. This is not an approval stage.</Alert><Field label="Reason for correction *" htmlFor="correction-reason" hint="At least 10 characters. This reason is visible to the company."><textarea id="correction-reason" rows={4} maxLength={1000} value={reason} onChange={(e)=>setReason(e.target.value)}/></Field>{error&&<Alert kind="error">{error}</Alert>}<div className="dialog-actions"><Button variant="secondary" onClick={()=>setCorrection(null)}>Cancel</Button><Button disabled={busy||reason.trim().length<10} onClick={async()=>{if(!correction)return;const created=await run({type:'openCorrection',assessmentId:correction.id,reason});if(created)setCorrection(null);}}>Create correction draft</Button></div></Dialog>
    <Dialog open={pause} title={org.active?'Pause this organization?':'Resume this organization?'} onClose={()=>setPause(false)}><p>{org.active?'Company representatives will retain read access to submitted results, but cannot save new assessment answers or submit.':'Company representatives will be able to continue editing and submitting in open cycles.'} No history will be deleted.</p><div className="dialog-actions"><Button variant="secondary" onClick={()=>setPause(false)}>Cancel</Button><Button disabled={busy} onClick={async()=>{const saved=await run({type:'setOrganizationActive',orgId:id,active:!org.active});if(saved)setPause(false);}}>Confirm</Button></div></Dialog>
  </>;
}
