import { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useCommand, useCurrentUser, useDatabase } from '../../app/hooks';
import { useAppSelector } from '../../app/store';
import { selectEffective } from '../../app/selectors';
import { canExport } from '../../domain/policies';
import { BANDS, BAND_LABELS } from '../../domain/scoring';
import { Alert, Badge, BandBadge, Button, Card, EmptyState, Field, Icon, Metric, PageHeading, formatDate } from '../../components/ui';
import { downloadBlob, preparePortfolioExport } from '../../infrastructure/downloads';
import { SECTORS } from '../company/Company';
export default function Portfolio() {
  const db=useDatabase();const user=useCurrentUser();const effective=useAppSelector(selectEffective);const {run,busy}=useCommand();
  const [params,setParams]=useSearchParams();const [exporting,setExporting]=useState(false);const [exportError,setExportError]=useState('');
  const cycleId=params.get('cycle')??Object.values(db.cycles).sort((a,b)=>b.opensAt.localeCompare(a.opensAt))[0]?.id??'';
  const sector=params.get('sector')??'';const band=params.get('band')??'';const search=params.get('q')??'';
  const setFilter=(key:string,value:string)=>{setParams((current)=>{const next=new URLSearchParams(current);if(value)next.set(key,value);else next.delete(key);return next;});};
  const rows=useMemo(()=>effective.filter((a)=>a.cycleId===cycleId&&a.snapshot&&(!sector||a.snapshot.organization.sector===sector)&&(!band||a.snapshot.result.band===band)&&a.snapshot.organization.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(b.submittedAt??'').localeCompare(a.submittedAt??'')),[effective,cycleId,sector,band,search]);
  const average=rows.length?rows.reduce((sum,a)=>sum+(a.snapshot?.result.overall??0),0)/rows.length:0;
  const draftCount=Object.values(db.assessments).filter((a)=>a.status==='draft'&&a.cycleId===cycleId&&(!sector||db.organizations[a.orgId]?.sector===sector)&&db.organizations[a.orgId]?.name.toLowerCase().includes(search.toLowerCase())).length;
  const exportRows=async(format:'csv'|'xlsx')=>{setExporting(true);setExportError('');try{const blob=await preparePortfolioExport(db,user,rows,format);const recorded=await run({type:'recordExport',format,count:rows.length});if(recorded)downloadBlob(`taleed-portfolio-${cycleId}.${format}`,blob);}catch(error){setExportError(error instanceof Error?error.message:'Export could not be prepared.');}finally{setExporting(false);}};
  return <><PageHeading eyebrow="TALEED PROGRAM WORKSPACE" title="Procurement portfolio" description="Understand participation and capability needs across the program's submitted assessments." actions={<><Button variant="secondary" disabled={busy||exporting||!rows.length||!canExport(user)} title={!canExport(user)?'Portfolio export permission is required.':undefined} onClick={()=>{void exportRows('csv');}}><Icon name="download"/>CSV</Button><Button disabled={busy||exporting||!rows.length||!canExport(user)} onClick={()=>{void exportRows('xlsx');}}><Icon name="download"/>{exporting?'Preparing…':'Export Excel'}</Button></>}/>
    <Card className="filters"><Field label="Assessment cycle" htmlFor="portfolio-cycle"><select id="portfolio-cycle" value={cycleId} onChange={(e)=>setFilter('cycle',e.target.value)}>{Object.values(db.cycles).sort((a,b)=>b.opensAt.localeCompare(a.opensAt)).map((c)=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field><Field label="Sector" htmlFor="portfolio-sector"><select id="portfolio-sector" value={sector} onChange={(e)=>setFilter('sector',e.target.value)}><option value="">All sectors</option>{SECTORS.map((s)=><option key={s}>{s}</option>)}</select></Field><Field label="Maturity band" htmlFor="portfolio-band"><select id="portfolio-band" value={band} onChange={(e)=>setFilter('band',e.target.value)}><option value="">All maturity bands</option>{BANDS.map((b)=><option key={b} value={b}>{BAND_LABELS[b]}</option>)}</select></Field><Field label="Company name" htmlFor="portfolio-search"><input id="portfolio-search" type="search" placeholder="Search companies…" value={search} onChange={(e)=>setFilter('q',e.target.value)}/></Field></Card>
    {exportError&&<Alert kind="error">{exportError}</Alert>}{!canExport(user)&&<Alert>You have read-only portfolio access. A Super Admin can grant export permission in People & access.</Alert>}
    <div className="metrics-grid"><Metric label="Effective submissions" value={rows.length} foot="One latest submitted revision per company" icon="file"/><Metric label="Average maturity" value={rows.length?`${average.toFixed(1)}%`:'—'} foot={`Calculated from ${rows.length} submitted results`} icon="chart"/><Metric label="Foundational companies" value={rows.filter((a)=>a.snapshot?.result.band==='foundational').length} foot="Among the filtered submitted results" icon="flag"/><Metric label="Open drafts" value={draftCount} foot="Cycle, sector and name filters; no band yet" icon="clock"/></div>
    <div className="cohort-note"><Icon name="info"/><span>Framework {db.cycles[cycleId]?.frameworkVersion??'—'} · n = {rows.length}. Drafts and earlier revisions are excluded from score averages. These are self-reported program results, not a market benchmark.</span></div>
    <div className="two-column"><Card><div className="card-heading"><h2>Maturity distribution</h2><Badge>{rows.length} companies</Badge></div><div className="distribution">{BANDS.map((b)=>{const count=rows.filter((a)=>a.snapshot?.result.band===b).length;return <div key={b}><div className="row-between"><BandBadge band={b}/><strong>{count}</strong></div><div className={`distribution-bar ${b}`}><span style={{width:`${rows.length?count/rows.length*100:0}%`}}/></div></div>;})}</div></Card><Card><div className="card-heading"><h2>Average capability scores</h2><Badge>Same filtered cohort</Badge></div><div className="aggregate-domains">{db.frameworks[db.cycles[cycleId]?.frameworkVersion??'']?.content.domains.map((domain,i)=>{const value=rows.length?rows.reduce((sum,a)=>sum+(a.snapshot?.result.domains[i]?.score??0),0)/rows.length:0;return <div key={domain.key}><div className="row-between"><span>{domain.name}</span><strong>{rows.length?`${value.toFixed(1)}%`:'—'}</strong></div><div className="score-track"><span style={{width:`${value}%`}}/></div></div>;})}</div></Card></div>
    <div className="section-title"><h2>Submitted companies</h2><span>{rows.length} result{rows.length===1?'':'s'}</span></div>{rows.length?<Card className="table-card"><div className="table-wrap"><table><caption className="sr-only">Filtered effective submitted assessments</caption><thead><tr><th>Company</th><th>Sector</th><th>Overall</th><th>Maturity</th><th>Submitted</th><th>Revision</th><th>Details</th></tr></thead><tbody>{rows.map((a)=><tr key={a.id}><td><Link to={`/app/organizations/${a.orgId}`}><strong>{a.snapshot?.organization.name}</strong></Link><small className="block">{a.snapshot?.organization.country}</small></td><td>{a.snapshot?.organization.sector}</td><td className="numeric"><strong>{a.snapshot?.result.overall.toFixed(1)}%</strong></td><td>{a.snapshot&&<BandBadge band={a.snapshot.result.band}/>}</td><td>{formatDate(a.submittedAt)}</td><td>v{a.revision}</td><td><Link to={`/app/results/${a.id}`}>View result</Link></td></tr>)}</tbody></table></div></Card>:<EmptyState title="No submitted results match these filters" action={<Button variant="secondary" onClick={()=>setParams({cycle:cycleId})}>Clear filters</Button>}>Adjust the filters or ask a Company Champion to complete and submit an assessment.</EmptyState>}</>;
}
