import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { useCommand, useCurrentUser, useDatabase } from '../../app/hooks';
import { useAppSelector } from '../../app/store';
import { selectOwnAssessments, selectOwnOrganization } from '../../app/selectors';
import { Alert, Badge, BandBadge, Button, Card, EmptyState, Field, Icon, LinkButton, Metric, PageHeading, Progress, formatDate } from '../../components/ui';
import { completion } from '../../domain/scoring';
import { effectiveSubmissions, isCycleOpen } from '../../domain/policies';
import { demoNow } from '../../domain/seed';

export const COUNTRIES = ['Saudi Arabia','United Arab Emirates','Bahrain','Kuwait','Oman','Qatar','Lebanon','Other'];
export const SECTORS = ['Manufacturing','Logistics','Energy','Technology','Construction','Professional services','Retail','Other'];
export const SIZES = ['1–10','11–50','51–200','201–500','501+'];
const profileSchema = z.object({ name:z.string().trim().min(2,'Enter the legal company name.').max(160),
  country:z.string().min(1,'Choose a country.'), sector:z.string().min(1,'Choose a sector.'), size:z.string().min(1,'Choose a company size.'),
  registrationId:z.string().trim().max(160), authorityConfirmed:z.boolean().refine(Boolean,'Confirm your authority to respond for this company.') });
export function Profile() {
  const org = useAppSelector(selectOwnOrganization); const user = useCurrentUser();
  const {run,busy}=useCommand(); const navigate=useNavigate(); const [saved,setSaved]=useState(false);
  const {register,handleSubmit,reset,formState:{errors,isDirty}}=useForm<z.infer<typeof profileSchema>>({resolver:zodResolver(profileSchema),
    defaultValues:{name:org?.name??'',country:org?.country??'',sector:org?.sector??'',size:org?.size??'',registrationId:org?.registrationId??'',authorityConfirmed:org?.authorityConfirmed??false}});
  useEffect(()=>{if(!isDirty)return; const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();}; window.addEventListener('beforeunload',warn); return()=>window.removeEventListener('beforeunload',warn);},[isDirty]);
  return <><PageHeading eyebrow={org?'COMPANY DETAILS':'GETTING STARTED · STEP 2 OF 2'} title={org?'Company profile':'Tell us about your company'} description="Identify the organization behind this assessment. These are proposed profile fields for the prototype."/>
    <div className="content-with-aside"><Card><form noValidate onSubmit={handleSubmit(async(values)=>{const id=await run({type:'saveProfile',profile:values});if(id){reset(values);setSaved(true);if(!org)navigate('/app/dashboard');}})}><div className="card-heading"><h2>Organization details</h2><Badge tone="blue">Identified assessment</Badge></div>
      <Field label="Legal company name *" htmlFor="company-name" error={errors.name?.message}><input id="company-name" autoComplete="organization" {...register('name')}/></Field><div className="form-grid"><Field label="Country *" htmlFor="country" error={errors.country?.message}><select id="country" {...register('country')}><option value="">Select country</option>{COUNTRIES.map((v)=><option key={v}>{v}</option>)}</select></Field><Field label="Sector *" htmlFor="sector" error={errors.sector?.message}><select id="sector" {...register('sector')}><option value="">Select sector</option>{SECTORS.map((v)=><option key={v}>{v}</option>)}</select></Field><Field label="Company size *" htmlFor="size" error={errors.size?.message}><select id="size" {...register('size')}><option value="">Select employee range</option>{SIZES.map((v)=><option key={v}>{v}</option>)}</select></Field><Field label="Registration reference (optional)" htmlFor="registration-id" error={errors.registrationId?.message} hint="Use a dummy reference in this prototype."><input id="registration-id" {...register('registrationId')}/></Field></div>
      <div className="divider"/><h3>Your authority to respond</h3><p className="muted">Respondent: <strong>{user.name}</strong> · {user.jobTitle}</p><label className="checkbox"><input type="checkbox" {...register('authorityConfirmed')}/><span>I am authorized to complete this self-assessment on behalf of the company and understand that results are self-reported.</span></label>{errors.authorityConfirmed&&<span className="field-error">{errors.authorityConfirmed.message}</span>}
      <div className="form-footer"><Button type="submit" disabled={busy}>{org?'Save company profile':'Save and continue'}<Icon name="arrow"/></Button>{isDirty&&<small className="muted">Unsaved profile changes</small>}</div>{saved&&!isDirty&&<Alert kind="success">Company profile saved. Earlier submitted reports retain their original company details.</Alert>}</form></Card><aside className="stack"><Card><span className="icon-box"><Icon name="info"/></span><h3>Why we ask</h3><p>Company information connects your submission to the right organization and lets the Taleed team understand participation across the program.</p><p>Duplicate company names or registration references are blocked in this local dataset.</p></Card><Alert kind="warning">No real company or personal information is needed for this demonstration. This is not a secure cloud account.</Alert></aside></div></>;
}
export function Dashboard() {
  const db=useDatabase(); const org=useAppSelector(selectOwnOrganization); const user=useCurrentUser();
  const own=useAppSelector(selectOwnAssessments); const {run,busy}=useCommand(); const navigate=useNavigate();
  const cycles=Object.values(db.cycles).sort((a,b)=>b.opensAt.localeCompare(a.opensAt));
  const [cycleId,setCycleId]=useState(cycles[0]?.id??'');
  if(!org)return <Navigate to="/app/profile" replace/>;
  const cycle=db.cycles[cycleId]; const records=own.filter((a)=>a.cycleId===cycleId);
  const current=records.find((a)=>a.status==='draft')??[...records].sort((a,b)=>b.revision-a.revision)[0];
  const framework=current?db.frameworks[current.frameworkVersion]?.content:cycle?db.frameworks[cycle.frameworkVersion]?.content:undefined;
  const answered=current?completion(current.answers):0;
  const resumeSection=framework?.domains.findIndex((d)=>d.questions.some((q)=>current?.answers[q.id]===null))??0;
  const resume=current?`/app/assessment/${current.id}/${Math.max(0,resumeSection)+1}`:'';
  const previous=own.find((a)=>a.status==='submitted'&&a.cycleId!==cycleId);
  const open=!!cycle&&isCycleOpen(cycle,demoNow())&&org.active;
  return <><PageHeading eyebrow="YOUR COMPANY WORKSPACE" title={`Welcome, ${user.name.split(' ')[0]}.`} description="A clear view of your procurement capabilities starts with an honest assessment." actions={<Field label="Assessment cycle" htmlFor="dashboard-cycle"><select id="dashboard-cycle" value={cycleId} onChange={(e)=>setCycleId(e.target.value)}>{cycles.map((c)=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field>}/>
    {!org.active&&<Alert kind="warning" title="Your organization is paused">Existing reports remain available. New answers and submissions are paused until the program team reactivates the organization.</Alert>}
    <div className="metrics-grid three"><Metric label="Current cycle" value={current?.status==='submitted'?'Submitted':current?'In progress':'Not started'} foot={cycle?.label??'No cycle available'} icon="file"/><Metric label="Questions answered" value={<>{answered}<span className="metric-suffix"> / 40</span></>} foot="Yes and No both count toward completion" icon="check"/><Metric label="Previous result" value={previous?.snapshot?`${previous.snapshot.result.overall.toFixed(1)}%`:'—'} foot={previous?db.cycles[previous.cycleId]?.label??'Prior cycle':'Your first result starts a historical record'} icon="chart"/></div>
    <Card className="workspace-hero"><div><Badge tone={current?.status==='submitted'?'success':'blue'}>{current?.status==='submitted'?'ASSESSMENT COMPLETE':current?.supersedesId?'CORRECTION DRAFT':'YOUR NEXT STEP'}</Badge><h2>{current?.status==='submitted'?'Your results are ready.':current?'Pick up where you left off.':'Begin your procurement assessment.'}</h2><p>{current?.status==='submitted'?'Explore your maturity result, compare your four domains and review the selected recommendations.':'Answer based on practices consistently in place today. You can move between sections and return later.'}</p>{current?.correctionReason&&<Alert kind="warning" title={`Correction revision ${current.revision}`}>{current.correctionReason} The earlier submission remains effective until you submit this revision.</Alert>}<div className="workspace-actions">{current?.status==='submitted'?<LinkButton to={`/app/results/${current.id}`}>View results <Icon name="arrow"/></LinkButton>:current?<><LinkButton to={resume}>Continue assessment <Icon name="arrow"/></LinkButton><LinkButton variant="secondary" to={`/app/assessment/${current.id}/review`}>Review answers</LinkButton></>:<Button disabled={busy||!open} onClick={async()=>{const id=await run({type:'startAssessment',cycleId});if(id)navigate(`/app/assessment/${id}/1`);}}>Start assessment <Icon name="arrow"/></Button>}</div>{!open&&<p className="muted">This cycle is closed or your company is paused. Saved results remain available.</p>}</div><div className="completion-panel"><span className="large-percentage">{Math.round(answered/40*100)}<small>%</small></span><span>completed</span><Progress value={answered}/><p>{answered} of 40 questions answered</p><small>This is completion, not a maturity score.</small></div></Card>
    <div className="section-title"><h2>Your four capability areas</h2><span>10 questions per section</span></div><div className="domain-card-grid">{framework?.domains.map((domain,i)=>{const count=domain.questions.filter((q)=>current?.answers[q.id]==='yes'||current?.answers[q.id]==='no').length;return <Card key={domain.key} className="domain-work-card"><div className="row-between"><span className="domain-number">0{i+1}</span><Badge tone={count===10?'success':count?'blue':'neutral'}>{count===10?'Complete':count?'In progress':'Not started'}</Badge></div><h3>{domain.name}</h3><Progress total={10} value={count} label={`${domain.name} completion`}/><div className="row-between"><small>{count} / 10 answered</small>{current&&<Link to={current.status==='submitted'?`/app/results/${current.id}`:`/app/assessment/${current.id}/${i+1}`} aria-label={`Open ${domain.name}`}><Icon name="arrow"/></Link>}</div></Card>;})}</div>
    <div className="two-column"><Card><h3>Answer for today, not tomorrow.</h3><p><strong>Yes</strong> means the practice is consistently in place across the procurement function. <strong>No</strong> includes gaps or partial implementation.</p><Link to="/methodology" className="text-link">Understand the methodology <Icon name="arrow"/></Link></Card><Card><h3>Your history stays intact.</h3><p>Submitted results cannot be edited directly. The program team can open a correction revision while preserving the original submission.</p><Link to="/app/history" className="text-link">View assessment history <Icon name="arrow"/></Link></Card></div></>;
}
export function History() {
  const db=useDatabase(); const own=useAppSelector(selectOwnAssessments);
  const effective=new Set(effectiveSubmissions(db).map((a)=>a.id));
  return <><PageHeading eyebrow="YOUR RECORD" title="Assessment history" description="Every submitted revision stays available. A new correction never overwrites the original."/>{own.length?<Card className="table-card"><div className="table-wrap"><table><caption className="sr-only">Your company's assessments and correction history</caption><thead><tr><th>Assessment cycle</th><th>Revision</th><th>Status</th><th>Result</th><th>Last updated</th><th>Open</th></tr></thead><tbody>{own.map((a)=><tr key={a.id}><td><strong>{db.cycles[a.cycleId]?.label}</strong>{a.correctionReason&&<small className="block">Correction: {a.correctionReason}</small>}</td><td>v{a.revision}</td><td><Badge tone={a.status==='draft'?'blue':effective.has(a.id)?'success':'neutral'}>{a.status==='draft'?'Draft':effective.has(a.id)?'Effective submission':'Earlier revision'}</Badge></td><td>{a.snapshot?<><strong>{a.snapshot.result.overall.toFixed(1)}%</strong> <BandBadge band={a.snapshot.result.band}/></>:'Not yet calculated'}</td><td>{formatDate(a.updatedAt)}</td><td><Link to={a.status==='draft'?`/app/assessment/${a.id}/review`:`/app/results/${a.id}`}>{a.status==='draft'?'Resume':'View result'}</Link></td></tr>)}</tbody></table></div></Card>:<EmptyState title="No assessments yet" action={<LinkButton to="/app/dashboard">Go to workspace</LinkButton>}>Your drafts and submitted reports will appear here.</EmptyState>}</>;
}
